[tool.poetry]
name = "graphs"
version = "0.1.0"
description = ""
authors = ["Santi Willy <santiwilly@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
ipython = "^6.5"
jupyter = "^1.0"
pandas = "^0.23.4"
matplotlib = "^2.2"

[tool.poetry.dev-dependencies]
